steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=us-central1-docker.pkg.dev/$PROJECT_ID/harness-chaos/harness-chaos', '.']

# To ensure tool is installed correctly
- name: 'us-central1-docker.pkg.dev/$PROJECT_ID/harness-chaos/harness-chaos'
  args: ['generate', '--help']

images: ['us-central1-docker.pkg.dev/$PROJECT_ID/harness-chaos/harness-chaos']